# Generated by Django 5.2.17 on 2026-09-13 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(choices=[('expression_atlas', 'EMBL-EBI Expression Atlas'), ('bvbrc', 'BV-BRC'), ('yeast_expression', 'Yeast Expression')], max_length=20)),
                ('organism', models.CharField(help_text="engine.domain.Host value, e.g. 'ecoli'.", max_length=20)),
                ('experiment_accession', models.CharField(max_length=100)),
                ('experiment_title', models.CharField(max_length=300)),
                ('comparison_id', models.CharField(max_length=100)),
                ('comparison_label', models.CharField(max_length=300)),
                ('experimental_condition', models.CharField(blank=True, max_length=200)),
                ('reference_condition', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('retrieved_at', models.DateTimeField(help_text='When this catalog entry was synced from the provider.')),
                ('analysis_method', models.CharField(blank=True, max_length=200)),
                ('publication_doi', models.CharField(blank=True, max_length=100)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='datasets.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'organism'], name='expression__provide_e70fa8_idx')],
            },
        ),
    ]
