# Generated by Django 5.2.17 on 2026-08-25 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('organism', models.CharField(help_text='e.g. E. coli', max_length=100)),
                ('biological_objective', models.TextField(blank=True, help_text='Base state, target state, and the logic behaviour being designed for.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='projects_pr_owner_i_b5bbe3_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_project_name_per_owner')],
            },
        ),
    ]
