"""Stage 5 — plasmid construction.

Turns a winning circuit into something a synthesis company can actually make.

Everything before this was sequence design. This stage is **assembly**: laying the parts
onto a backbone in the right order with the right flanking elements, and checking the
result against an iGEM assembly standard. A circuit that cannot be ordered is not a
result.

The output is the first artefact a researcher would put money behind, so the compliance
check matters more than it looks. A single unnoticed restriction site turns a plasmid
order into a wasted month.

**Built for the `direct` path** (docs/plasmids.md §3, §6): a direct submission has one
trigger and one switch, so ``pipeline.py`` hand-builds a trivial one-gene
``CircuitCandidate`` the same way it hand-builds the one ``TriggerCandidate`` for
stages 1-2, and this stage does not need stage 4 (``CircuitDesigner``) to exist.

**Optional explicit codon optimisation.** ``params.payload.optimize_codons`` selects
one clean synonymous variant through the
shared host optimizer before context folding. Exact source/optimized digests, changed
codon count, seed and unresolved constraints are recorded. Without this explicit flag,
source payloads remain unchanged before the defined fusion junction.

**Biopython stays confined to this module** (ADR 0007, docs/plasmids.md §5) —
``PlasmidBuilder`` itself works entirely in CERNAL's own
``Segment``/``Plasmid``/``PlasmidDesign`` types plus ``sequences.py`` and
``MotifScreener``. ``to_genbank`` (export) and ``parse_custom_backbone`` (the reverse,
docs/plasmids.md Q13/ROADMAP E5b) are the only two functions here that touch it; a
``SeqRecord`` is built and discarded inside each, never crossing back into engine or
Platform code.

**``sbol3`` is confined the same way** (ADR 0008). ``to_sbol3`` is the only function
that imports it, builds a ``Document`` and discards it; no SBOL type reaches engine or
Platform code either. ``sbol-utilities`` is deliberately absent — its GenBank converter
calls ``SeqFeature.strand``, which the Biopython above removed.
"""

import hashlib
import io
import json
from functools import cache
from pathlib import Path

import sbol3
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqFeature import CompoundLocation, ExactPosition, SeqFeature, SimpleLocation
from Bio.SeqRecord import SeqRecord

from engine import sequences as sq
from engine.domain import (
    AssemblyStandard,
    CircuitCandidate,
    DesiredOutcome,
    GateDesign,
    GateKind,
    Host,
    LogicOperator,
    Plasmid,
    PlasmidDesign,
    Segment,
    SegmentKind,
)
from engine.errors import InputValidationError
from engine.gates.tools.codons import CodonOptimizer
from engine.stages.motifs import MotifScreener

# --- Parts table (docs/plasmids.md §4; docs/ROADMAP.md Q11/Q12/Q13) ----------------
#
# Community-standard defaults, verified against the iGEM Registry API
# (https://api.registry.igem.org/v1/parts) rather than typed from memory — CLAUDE.md
# §1's "an almost-right CDS is far worse than a missing one" applies as much to a
# promoter as to a payload. These are provisional defaults, not a scientific decision
# made on the team's behalf: any entry can be replaced without touching
# ``PlasmidBuilder`` itself. A host or outcome with no entry raises a clear
# ``InputValidationError`` naming what is missing, rather than silently assembling a
# promoter-less or payload-less plasmid.

#: The iGEM Registry part each table entry below is a copy of, keyed by the local part
#: name. The naming is irregular and that is exactly why this is declared rather than
#: derived: the basic parts carry a ``BBa_`` prefix, the payload's registry name
#: (``BBa_E0040``) says nothing about its local name (``GFP``), and the plasmid
#: backbones are registered under their bare names with no prefix at all.
#:
#: This is identity only — never sequence. The tables below stay the single source of
#: truth for what CERNAL builds (CLAUDE.md §1); storing the sequences a second time,
#: here or in the bundled catalog, is how two copies of one part drift apart.
#: ``tools/sync_registry_parts.py`` refreshes ``data/registry/parts.json`` from this
#: mapping, and ``tests/engine/test_registry_parts.py`` fails if a table sequence stops
#: matching the Registry part it claims to be.
REGISTRY_PARTS: dict[str, str] = {
    "K404108": "BBa_K404108",
    "I712004": "BBa_I712004",
    "J23119": "BBa_J23119",
    "K124002": "BBa_K124002",
    "B0015": "BBa_B0015",
    "K1486025": "BBa_K1486025",
    "GFP": "BBa_E0040",
    "mCherry": "BBa_J06504",
    "Firefly_luciferase": "BBa_I712019",
    "pSB1A3": "pSB1A3",
    "pSB1C3": "pSB1C3",
    "pSB1K3": "pSB1K3",
    "pSB1T3": "pSB1T3",
    "pSB1AK3": "pSB1AK3",
    "pSB1AT3": "pSB1AT3",
    "pSB3C5": "pSB3C5",
    "pSB3K3": "pSB3K3",
    "pSB3T5": "pSB3T5",
    "pSB4C5": "pSB4C5",
}

#: (part name, DNA sequence) per host. Human uses the Registry's CMV expression
#: promoter and hGH polyadenylation signal below. Its pipeline defaults to no
#: restriction-based assembly protocol; a custom mammalian backbone or a bare
#: expression cassette is supported (docs/plasmids.md).
PROMOTERS: dict[Host, tuple[str, str]] = {
    # Registry BBa_I712004 — CMV promoter. Verified from the Registry API.
    Host.HUMAN: (
        "I712004",
        "CGATGTACGGGCCAGATATACGCGTTGACATTGATTATTGCCTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTC"
        "ATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGCCCAACGACCCCCGCCCA"
        "TTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCCATTGACGTCAATGGGTGGAGTATTTACG"
        "GTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCCCCTATTGACGTCAATGACGGTAAATGGC"
        "CCGCCTGGCATTATGCCCAGTACATGACCTTATGGGACTTTCCTACTTGGCAGTACATCTACGTATTAGTCATCGCTATT"
        "ACCATGGTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTGACTCACGGGGATTTCCAAGTCTCCACCC"
        "CATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCAAAATGTCGTAACAACTCCGCCCCATTGA"
        "CGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCTCTCTGGCTAACTAGAGAACCCACTGCTTAC"
        "TGGCTTATCGAAAT",
    ),
    # BBa_J23119 — Anderson promoter family: the consensus sequence and the strongest
    # constitutive member. https://registry.igem.org/parts/bba-j23119
    Host.ECOLI: ("J23119", "TTGACAGCTAGCTCAGTCCTAGGTATAATGCTAGC"),
    # The same Anderson part, and that is the finding rather than a shortcut. Nevot et al.
    # (Cell Systems 16(2):101169, 2025, doi:10.1016/j.cels.2025.101169) compared nine
    # endogenous C. acnes promoters against the synthetic consensus BBa_J23119 and J23119
    # gave the HIGHEST expression; all six fluorescent reporters in their deposited
    # plasmid collection are built on P(BBa_J23119)+RBS_1, and Addgene's depositor note
    # for the sfGFP vector (#225611) calls it "strong constitutive recombinant expression
    # in C. acnes". Known caveat: its expression decays in stationary phase.
    Host.C_ACNES: ("J23119", "TTGACAGCTAGCTCAGTCCTAGGTATAATGCTAGC"),
    # BBa_K124002 — the yeast GPD (TDH3) promoter: 680 bp upstream of GPD1, a very
    # strong constitutive promoter (Mumberg, Muller & Funk 1995, p413 pGPD,
    # doi:10.1016/0378-1119(95)00037-7). https://registry.igem.org/parts/bba-k124002
    Host.YEAST: (
        "K124002",
        "TCAGTTCGAGTTTATCATTATCAATACTGCCATTTCAAAGAATACGTAAATAATTAATAGTAGTGATTTTCCTAACTT"
        "TATTTAGTCAAAAAATTAGCCTTTTAATTCTGCTGTAACCCGTACATGCCCAAAATAGGGGGCGGGTTACACAGAAT"
        "ATATAACATCGTAGGTGTCTGGGTGAACAGTTTATTCCTGGCATCCACTAAATATAATGGAGCCCGCTTTTTAAGCT"
        "GGCATCCAGAAAAAAAAAGAATCCCAGCACCAAAATATTGTTTTCTTCACCAACCATCAGTTCATAGGTCCATTCTC"
        "TTAGCGCAACTACAGAGAACAGGGGCACAAACAGGCAAAAAACGGGCACAACCTCAATGGAGTGATGCAACCTGCCT"
        "GGAGTAAATGATGACACAAGGCAATTGACCCACGCATGTATCTATCTCATTTTCTTACACCTTCTATTACCTTCTGC"
        "TCTCTCTGATTTGGAAAAAGCTGAAAAAAAAGGTTGAAACCAGTTCCCTGAAATTATTCCCCTACTTGACTAATAAG"
        "TATATAAAGACGGTAGGTATTGATTGTAATTCTGTAAATCTATTTCTTAAACTTCTTAAATTCTACTTTTATAGTTA"
        "GTCTTTTTTTTAGTTTTAAAACACCAAGAACTTAGTTTCGAATAAACACACATAAACAAACAAA",
    ),
}

#: (part name, DNA sequence) per host. Same coverage and reasoning as ``PROMOTERS``.
TERMINATORS: dict[Host, tuple[str, str]] = {
    # Registry BBa_K404108 — hGH terminator. Verified from the Registry API.
    Host.HUMAN: (
        "K404108",
        "GACGGGTGGCATCCCTGTGACCCCTCCCCAGTGCCTCTCCTGGCCCTGGAAGTTGCCACTCCAGTGCCCACCAGCCTTGT"
        "CCTAATAAAATTAAGTTGCATCATTTTGTCTGACTAGGTGTCCTTCTATAATATTATGGGGTGGAGGGGGGTGGTATGGA"
        "GCAAGGGGCAAGTTGGGAAGACAACCTGTAGGGCCTGCGGGGTCTATTGGGAACCAAGCTGGAGTGCAGTGGCACAATCT"
        "TGGCTCACTGCAATCTCCGCCTCCTGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCCGAGTTGTTGGGATTCCAGGCATG"
        "CATGACCAGGCTCAGCTAATTTTTGTTTTTTTGGTAGAGACGGGGTTTCACCATATTGGCCAGGCTGGTCTCCAACTCCT"
        "AATCTCAGGTGATCTACCCACCTTGGCCTCCCAAATTGCTGGGATTACAGGCGTGAACCACTGCTCCCTTCCCTGTCCTT"
        "T",
    ),
    # BBa_B0015 — double terminator (B0010 + B0012), the most-used terminator in the
    # registry. https://registry.igem.org/parts/BBa_B0015
    Host.ECOLI: (
        "B0015",
        "CCAGGCATCAAATAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTTTCGTTTTATCTGTTGTTTGTCGGTGAACGC"
        "TCTCTACTAGAGTCACACTGGCTCACCTTCGGGTGGGCCTTTCTGCGTTTATA",
    ),
    # BBa_B0015 again, and unlike the promoter above this one is TRANSFERRED BY ANALOGY,
    # not measured in this host. No terminator part is named anywhere in the AIS-China or
    # Nevot et al. plasmid collections, and both papers are paywalled, so there is no
    # characterised C. acnes terminator to bundle.
    #
    # Why it is defensible rather than a guess: high-GC Actinomycetota terminators
    # characteristically pair a stable GC-rich hairpin with a weak or absent U-tract (~90%
    # of M. tuberculosis terminators have no U-trail or a mixed U/A trail), and
    # mycobacterial RNAP terminates MORE efficiently than E. coli RNAP at canonical
    # terminators with imperfect U-tracts. B0015 is hairpin + a short 4 nt U-tract, which
    # is the regime that work says transfers. The one dissenting result concerns
    # terminators LACKING a U-tract; B0015 has one. And J23119 above is direct precedent
    # for an E. coli synthetic part outperforming native ones in this exact organism.
    #
    # The residual risk is real and the scoring cannot see it: transcriptional read-through
    # is invisible to ``predicted_leakage``, which is computed from the switch's own
    # folding and has no term for polymerase arriving from the plasmid context. A
    # read-through failure would score clean, clear the 0.85 hard filter and leak in the
    # lab. ``build`` records this on the design so it reaches the researcher.
    Host.C_ACNES: (
        "B0015",
        "CCAGGCATCAAATAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTTTCGTTTTATCTGTTGTTTGTCGGTGAACGC"
        "TCTCTACTAGAGTCACACTGGCTCACCTTCGGGTGGGCCTTTCTGCGTTTATA",
    ),
    # BBa_K1486025 — the yeast ADH1 terminator, extracted by PCR from an Addgene
    # plasmid; used in 22 real registry constructs.
    # https://registry.igem.org/parts/bba-k1486025
    Host.YEAST: (
        "K1486025",
        "GCGAATTTCTTATGATTTATGATTTTTATTATTAAATAAGTTATAAAAAAAATAAGTGTATACAAATTTTAAAGTGA"
        "CTCTTAGGTTTTAAAACGAAAATTCTTATTCTTGAGTAACTCTTTCCTGTAGGTCAGGTTGCTTTCTCAGGTATAGT"
        "ATGAGGTCGCTCTTATTGACCACACCTCTACCGG",
    ),
}

#: (part name, DNA sequence) per requested outcome. GFP, mCherry and firefly luciferase are pinned —
#: docs/ROADMAP.md Q11. ``DesiredOutcome.CUSTOM`` is never a key here; a custom payload
#: always comes from the caller (``params["payload"]["custom_sequence"]``), validated
#: by the same :func:`validate_payload_cds` every table entry passes through too.
PAYLOADS: dict[DesiredOutcome, tuple[str, str]] = {
    # BBa_E0040 — GFPmut3b, the most-used reporter CDS in the registry. Ends in a
    # tandem stop (UAA UAA) — validate_payload_cds treats a trailing run of stop
    # codons as one stop rather than N premature ones; a real CDS this common is what
    # surfaced that the rule needed to exist (docs/plasmids.md §7).
    # https://registry.igem.org/parts/BBa_E0040
    DesiredOutcome.GFP: (
        "GFP",
        "ATGCGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCAC"
        "AAATTTTCTGTCAGTGGAGAGGGTGAAGGTGATGCAACATACGGAAAACTTACCCTTAAATTTATTTGCACTAC"
        "TGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTTTCGGTTATGGTGTTCAATGCTTTGCGAGATACC"
        "CAGATCATATGAAACAGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAAAGAACTATATTT"
        "TTCAAAGATGACGGGAACTACAAGACACGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATAGAATCGA"
        "GTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTTGGACACAAATTGGAATACAACTATAACTCACACA"
        "ATGTATACATCATGGCAGACAAACAAAAGAATGGAATCAAAGTTAACTTCAAAATTAGACACAACATTGAAGAT"
        "GGAAGCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAA"
        "CCATTACCTGTCCACACAATCTGCCCTTTCGAAAGATCCCAACGAAAAGAGAGACCACATGGTCCTTCTTGAGT"
        "TTGTAACAGCTGCTGGGATTACACATGGCATGGATGAACTATACAAATAATAA",
    ),
    # BBa_J06504: exact Registry CDS, revision 2021-09-08T20:23:04.000Z.
    DesiredOutcome.MCHERRY: (
        "mCherry",
        "ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGGGCTCCGT"
        "GAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGA"
        "CCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCAC"
        "CCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGG"
        "CGGCGTGGTGACCGTGACCCAGGACTCCTCCTTGCAGGACGGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACT"
        "TCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCTCCGAGCGGATGTACCCCGAGGACGGC"
        "GCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAA"
        "GGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACA"
        "CCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAATAA",
    ),
    # BBa_I712019: exact Registry CDS, revision 2021-09-08T20:22:52.000Z.
    DesiredOutcome.LUCIFERASE: (
        "Firefly_luciferase",
        "ATGGAAGACGCCAAAAACATAAAGAAAGGCCCGGCGCCATTCTATCCGCTGGAAGATGGAACCGCTGGAGAGCAACTGCA"
        "TAAGGCTATGAAGAGATACGCCCTGGTTCCTGGAACAATTGCTTTTACAGATGCACATATCGAGGTGGACATCACTTACG"
        "CTGAGTACTTCGAAATGTCCGTTCGGTTGGCAGAAGCTATGAAACGATATGGGCTGAATACAAATCACAGAATCGTCGTA"
        "TGCAGTGAAAACTCTCTTCAATTCTTTATGCCGGTGTTGGGCGCGTTATTTATCGGAGTTGCAGTTGCGCCCGCGAACGA"
        "CATTTATAATGAACGTGAATTGCTCAACAGTATGGGCATTTCGCAGCCTACCGTGGTGTTCGTTTCCAAAAAGGGGTTGC"
        "AAAAAATTTTGAACGTGCAAAAAAAGCTCCCAATCATCCAAAAAATTATTATCATGGATTCTAAAACGGATTACCAGGGA"
        "TTTCAGTCGATGTACACGTTCGTCACATCTCATCTACCTCCCGGTTTTAATGAATACGATTTTGTGCCAGAGTCCTTCGA"
        "TAGGGACAAGACAATTGCACTGATCATGAACTCCTCTGGATCTACTGGTCTGCCTAAAGGTGTCGCTCTGCCTCATAGAA"
        "CTGCCTGCGTGAGATTCTCGCATGCCAGAGATCCTATTTTTGGCAATCAAATCATTCCGGATACTGCGATTTTAAGTGTT"
        "GTTCCATTCCATCACGGTTTTGGAATGTTTACTACACTCGGATATTTGATATGTGGATTTCGAGTCGTCTTAATGTATAG"
        "ATTTGAAGAAGAGCTGTTTCTGAGGAGCCTTCAGGATTACAAGATTCAAAGTGCGCTGCTGGTGCCAACCCTATTCTCCT"
        "TCTTCGCCAAAAGCACTCTGATTGACAAATACGATTTATCTAATTTACACGAAATTGCTTCTGGTGGCGCTCCCCTCTCT"
        "AAGGAAGTCGGGGAAGCGGTTGCCAAGAGGTTCCATCTGCCAGGTATCAGGCAAGGATATGGGCTCACTGAGACTACATC"
        "AGCTATTCTGATTACACCCGAGGGGGATGATAAACCGGGCGCGGTCGGTAAAGTTGTTCCATTTTTTGAAGCGAAGGTTG"
        "TGGATCTGGATACCGGGAAAACGCTGGGCGTTAATCAAAGAGGCGAACTGTGTGTGAGAGGTCCTATGATTATGTCCGGT"
        "TATGTAAACAATCCGGAAGCGACCAACGCCTTGATTGACAAGGATGGATGGCTACATTCTGGAGACATAGCTTACTGGGA"
        "CGAAGACGAACACTTCTTCATCGTTGACCGCCTGAAGTCTCTGATTAAGTACAAAGGCTATCAGGTGGCTCCCGCTGAAT"
        "TGGAATCCATCTTGCTCCAACACCCCAACATCTTCGACGCAGGTGTCGCAGGTCTTCCCGACGATGACGCCGGTGAACTT"
        "CCCGCCGCCGTTGTTGTTTTGGAGCACGGAAAGACGATGACGGAAAAAGAGATCGTGGATTACGTCGCCAGTCAAGTAAC"
        "AACCGCGAAAAAGTTGCGCGGAGGAGTTGTGTTTGTGGACGAAGTACCGAAAGGTCTTACCGGAAAACTCGACGCAAGAA"
        "AAATCAGAGAGATCCTCATAAAGGCCAAGAAGGGCGGAAAGATCGCCGTGTAA",
    ),
    # GenBank J01749.1, annotated beta-lactamase CDS; exact protein checked.
    DesiredOutcome.ANTIBIOTIC: (
        "AmpR",
        "ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAAC"
        "GCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGA"
        "TCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCC"
        "CGTGTTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCAC"
        "AGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCA"
        "ACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTT"
        "GATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGCAGCAATGGCAACAAC"
        "GTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAG"
        "TTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCT"
        "CGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAAC"
        "TATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAA",
    ),
    # GenBank V00618.1, annotated neomycin phosphotransferase CDS; exact protein checked.
    DesiredOutcome.KANAMYCIN: (
        "KanR",
        "ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACA"
        "GACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGT"
        "CCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTG"
        "CTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCT"
        "TGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCG"
        "ACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAA"
        "GAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGCATGCCCGACGGCGAGGATCTCGTCGTGAC"
        "CCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTG"
        "TGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTC"
        "CTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGA",
    ),
}


EXTERNAL_PARTS = {"AmpR": "J01749.1", "KanR": "V00618.1"}
PAYLOAD_HOSTS = {
    outcome: (
        (Host.ECOLI,)
        if outcome in (DesiredOutcome.ANTIBIOTIC, DesiredOutcome.KANAMYCIN)
        else tuple(Host)
    )
    for outcome in (*PAYLOADS, DesiredOutcome.CUSTOM)
}


#: (catalog key -> (name, DNA sequence)). Real BioBrick/RFC10 assembly vectors from
#: the iGEM Registry (docs/plasmids.md Q13, docs/ROADMAP.md E5b) spanning three
#: resistance markers and three copy-number classes (high: pUC/pMB1 ori; medium: p15A;
#: low: pSC101) so a researcher's choice reflects a real lab decision, not a single
#: default. The registry exposes each vector's full sequence but no feature-level
#: annotation (no coordinate for where the origin ends and the marker begins), so each
#: entry is stored as one opaque backbone segment rather than split into fabricated
#: sub-segments with guessed boundaries (CLAUDE.md §1). A caller's own uploaded GenBank
#: (:func:`parse_custom_backbone`) is treated the same way, for the same reason.
BACKBONES: dict[str, tuple[str, str]] = {
    # pSB1A3 — Amp resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1a3
    "psb1a3": (
        "pSB1A3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCACAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATATAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB1C3 — Cm resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1c3
    "psb1c3": (
        "pSB1C3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCACAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCGAGGCTTGGATTCTCACCAATAAAAAACGCCCGGCGGCAACCGAGCGTTCTGAACAAATCCAGATGGAGTTCTGAGGTCATTACTGGATCTATCAACAGGAGTCCAAGCGAGCTCGATATCAAATTACGCCCCGCCCTGCCACTCATCGCAGTACTGTTGTAATTCATTAAGCATTCTGCCGACATGGAAGCCATCACAAACGGCATGATGAACCTGAATCGCCAGCGGCATCAGCACCTTGTCGCCTTGCGTATAATATTTGCCCATGGTGAAAACGGGGGCGAAGAAGTTGTCCATATTGGCCACGTTTAAATCAAAACTGGTGAAACTCACCCAGGGATTGGCTGAGACGAAAAACATATTCTCAATAAACCCTTTAGGGAAATAGGCCAGGTTTTCACCGTAACACGCCACATCTTGCGAATATATGTGTAGAAACTGCCGGAAATCGTCGTGGTATTCACTCCAGAGCGATGAAAACGTTTCAGTTTGCTCATGGAAAACGGTGTAACAAGGGTGAACACTATCCCATATCACCAGCTCACCGTCTTTCATTGCCATACGAAATTCCGGATGAGCATTCATCAGGCGGGCAAGAATGTGAATAAAGGCCGGATAAAACTTGTGCTTATTTTTCTTTACGGTCTTTAAAAAGGCCGTAATATCCAGCTGAACGGTCTGGTTATAGGTACATTGAGCAACTGACTGAAATGCCTCAAAATGTTCTTTACGATGCCATTGGGATATATCAACGGTGGTATATCCAGTGATTTTTTTCTCCATTTTAGCTTCCTTAGCTCCTGAAAATCTCGATAACTCAAAAAATACGCCCGGTAGTGATCTTATTTCATTATGGTGAAAGTTGGAACCTCTTACGTGCCCGATCAACTCGAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB1K3 — Kan resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1k3
    "psb1k3": (
        "pSB1K3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCACAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCGAGTCCCGTCAAGTCAGCGTAATGCTCTGCCAGTGTTACAACCAATTAACCAATTCTGATTAGAAAAACTCATCGAGCATCAAATGAAACTGCAATTTATTCATATCAGGATTATCAATACCATATTTTTGAAAAAGCCGTTTCTGTAATGAAGGAGAAAACTCACCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATCGGTCTGCGATTCCGACTCGTCCAACATCAATACAACCTATTAATTTCCCCTCGTCAAAAATAAGGTTATCAAGTGAGAAATCACCATGAGTGACGACTGAATCCGGTGAGAATGGCAAAAGCTTATGCATTTCTTTCCAGACTTGTTCAACAGGCCAGCCATTACGCTCGTCATCAAAATCACTCGCATCAACCAAACCGTTATTCATTCGTGATTGCGCCTGAGCGAGACGAAATACGCGATCGCTGTTAAAAGGACAATTACAAACAGGAATCGAATGCAACCGGCGCAGGAACACTGCCAGCGCATCAACAATATTTTCACCTGAATCAGGATATTCTTCTAATACCTGGAATGCTGTTTTCCCGGGGATCGCAGTGGTGAGTAACCATGCATCATCAGGAGTACGGATAAAATGCTTGATGGTCGGAAGAGGCATAAATTCCGTCAGCCAGTTTAGTCTGACCATCTCATCTGTAACATCATTGGCAACGCTACCTTTGCCATGTTTCAGAAACAACTCTGGCGCATCGGGCTTCCCATACAATCGATAGATTGTCGCACCTGATTGCCCGACATTATCGCGAGCCCATTTATACCCATATAAATCAGCATCCATGTTGGAATTTAATCGCGGCCTGGAGCAAGACGTTTCCCGTTGAATATGGCTCATAACACCCCTTGTATTACTGTTTATGTAAGCAGACAGTTTTATTGTTCATGATGATATATTTTTATCTTGTGCAATGTAACATCAGAGATTTTGAGACACAACGTGGCTTTGTTGAATAAATCGAACTTTTGCTGAGTTGAAGGATCAGCTCGAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB1T3 — Tet resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1t3
    "psb1t3": (
        "pSB1T3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCACAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCGAGATTCTCATGTTTGACAGCTTATCATCGATAAGCTTTAATGCGGTAGTTTATCACAGTTAAATTGCTAACGCAGTCAGGCACCGTGTATGAAATCTAACAATGCGCTCATCGTCATCCTCGGCACCGTCACCCTGGATGCTGTAGGCATAGGCTTGGTTATGCCGGTACTGCCGGGCCTCTTGCGGGATATCGTCCATTCCGACAGCATCGCCAGTCACTATGGCGTGCTGCTAGCGCTATATGCGTTGATGCAATTTCTATGCGCACCCGTTCTCGGAGCACTGTCCGACCGCTTTGGCCGCCGCCCAGTCCTGCTCGCTTCGCTACTTGGAGCCACTATCGACTACGCGATCATGGCGACCACACCCGTCCTGTGGATCCTCTACGCCGGACGCATCGTGGCCGGCATCACCGGCGCCACAGGTGCGGTTGCTGGCGCCTATATCGCCGACATCACCGATGGGGAAGATCGGGCTCGCCACTTCGGGCTCATGAGCGCTTGTTTCGGCGTGGGTATGGTGGCAGGCCCCGTGGCCGGGGGACTGTTGGGCGCCATCTCCTTGCATGCACCATTCCTTGCGGCGGCGGTGCTCAACGGCCTCAACCTACTACTGGGCTGCTTCCTAATGCAGGAGTCGCATAAGGGAGAGCGTCGACCGATGCCCTTGAGAGCCTTCAACCCAGTCAGCTCCTTCCGGTGGGCGCGGGGCATGACTATCGTCGCCGCACTTATGACTGTCTTCTTTATCATGCAACTCGTAGGACAGGTGCCGGCAGCGCTCTGGGTCATTTTCGGCGAGGACCGCTTTCGCTGGAGCGCGACGATGATCGGCCTGTCGCTTGCGGTATTCGGAATCTTGCACGCCCTCGCTCAAGCCTTCGTCACTGGTCCCGCCACCAAACGTTTCGGCGAGAAGCAGGCCATTATCGCCGGCATGGCGGCCGACGCGCTGGGCTACGTCTTGCTGGCGTTCGCGACGCGAGGCTGGATGGCCTTCCCCATTATGATTCTTCTCGCTTCCGGCGGCATCGGGATGCCCGCGTTGCAGGCCATGCTGTCCAGGCAGGTAGATGACGACCATCAGGGACAGCTTCAAGGATCGCTCGCGGCTCTTACCAGCCTAACTTCGATCACTGGACCGCTGATCGTCACGGCGATTTATGCCGCCTCGGCGAGCACATGGAACGGGTTGGCATGGATTGTAGGCGCCGCCCTATACCTTGTCTGCCTCCCCGCGTTGCGTCGCGGTGCATGGAGCCGGGCCACCTCGACCTAACTCGAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB1AK3 — Amp+Kan resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1ak3
    "psb1ak3": (
        "pSB1AK3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGGACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCGAGTCCCGTCAAGTCAGCGTAATGCTCTGCCAGTGTTACAACCAATTAACCAATTCTGATTAGAAAAACTCATCGAGCATCAAATGAAACTGCAATTTATTCATATCAGGATTATCAATACCATATTTTTGAAAAAGCCGTTTCTGTAATGAAGGAGAAAACTCACCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATCGGTCTGCGATTCCGACTCGTCCAACATCAATACAACCTATTAATTTCCCCTCGTCAAAAATAAGGTTATCAAGTGAGAAATCACCATGAGTGACGACTGAATCCGGTGAGAATGGCAAAAGCTTATGCATTTCTTTCCAGACTTGTTCAACAGGCCAGCCATTACGCTCGTCATCAAAATCACTCGCATCAACCAAACCGTTATTCATTCGTGATTGCGCCTGAGCGAGACGAAATACGCGATCGCTGTTAAAAGGACAATTACAAACAGGAATCGAATGCAACCGGCGCAGGAACACTGCCAGCGCATCAACAATATTTTCACCTGAATCAGGATATTCTTCTAATACCTGGAATGCTGTTTTCCCGGGGATCGCAGTGGTGAGTAACCATGCATCATCAGGAGTACGGATAAAATGCTTGATGGTCGGAAGAGGCATAAATTCCGTCAGCCAGTTTAGTCTGACCATCTCATCTGTAACATCATTGGCAACGCTACCTTTGCCATGTTTCAGAAACAACTCTGGCGCATCGGGCTTCCCATACAATCGATAGATTGTCGCACCTGATTGCCCGACATTATCGCGAGCCCATTTATACCCATATAAATCAGCATCCATGTTGGAATTTAATCGCGGCCTGGAGCAAGACGTTTCCCGTTGAATATGGCTCATAACACCCCTTGTATTACTGTTTATGTAAGCAGACAGTTTTATTGTTCATGATGATATATTTTTATCTTGTGCAATGTAACATCAGAGATTTTGAGACACAACGTGGCTTTGTTGAATAAATCGAACTTTTGCTGAGTTGAAGGATCAGCTCGAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB1AT3 — Amp+Tet resistance, high (pUC/pMB1 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb1at3
    "psb1at3": (
        "pSB1AT3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGGACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGCTCGAGATTCTCATGTTTGACAGCTTATCATCGATAAGCTTTAATGCGGTAGTTTATCACAGTTAAATTGCTAACGCAGTCAGGCACCGTGTATGAAATCTAACAATGCGCTCATCGTCATCCTCGGCACCGTCACCCTGGATGCTGTAGGCATAGGCTTGGTTATGCCGGTACTGCCGGGCCTCTTGCGGGATATCGTCCATTCCGACAGCATCGCCAGTCACTATGGCGTGCTGCTAGCGCTATATGCGTTGATGCAATTTCTATGCGCACCCGTTCTCGGAGCACTGTCCGACCGCTTTGGCCGCCGCCCAGTCCTGCTCGCTTCGCTACTTGGAGCCACTATCGACTACGCGATCATGGCGACCACACCCGTCCTGTGGATCCTCTACGCCGGACGCATCGTGGCCGGCATCACCGGCGCCACAGGTGCGGTTGCTGGCGCCTATATCGCCGACATCACCGATGGGGAAGATCGGGCTCGCCACTTCGGGCTCATGAGCGCTTGTTTCGGCGTGGGTATGGTGGCAGGCCCCGTGGCCGGGGGACTGTTGGGCGCCATCTCCTTGCATGCACCATTCCTTGCGGCGGCGGTGCTCAACGGCCTCAACCTACTACTGGGCTGCTTCCTAATGCAGGAGTCGCATAAGGGAGAGCGTCGACCGATGCCCTTGAGAGCCTTCAACCCAGTCAGCTCCTTCCGGTGGGCGCGGGGCATGACTATCGTCGCCGCACTTATGACTGTCTTCTTTATCATGCAACTCGTAGGACAGGTGCCGGCAGCGCTCTGGGTCATTTTCGGCGAGGACCGCTTTCGCTGGAGCGCGACGATGATCGGCCTGTCGCTTGCGGTATTCGGAATCTTGCACGCCCTCGCTCAAGCCTTCGTCACTGGTCCCGCCACCAAACGTTTCGGCGAGAAGCAGGCCATTATCGCCGGCATGGCGGCCGACGCGCTGGGCTACGTCTTGCTGGCGTTCGCGACGCGAGGCTGGATGGCCTTCCCCATTATGATTCTTCTCGCTTCCGGCGGCATCGGGATGCCCGCGTTGCAGGCCATGCTGTCCAGGCAGGTAGATGACGACCATCAGGGACAGCTTCAAGGATCGCTCGCGGCTCTTACCAGCCTAACTTCGATCACTGGACCGCTGATCGTCACGGCGATTTATGCCGCCTCGGCGAGCACATGGAACGGGTTGGCATGGATTGTAGGCGCCGCCCTATACCTTGTCTGCCTCCCCGCGTTGCGTCGCGGTGCATGGAGCCGGGCCACCTCGACCTAACTCGAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB3C5 — Cm resistance, medium (p15A ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb3c5
    "psb3c5": (
        "pSB3C5",
        "TACTAGTAGCGGCCGCTGCAGGAGTCACTAAGGGTTAGTTAGTTAGATTAGCAGAAAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTAAAACTTCCCTTGGGGTTATCATTGGGGCTCACTCAAAGGCGGTAATCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGCTAGAGATGGAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATAATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCTTAATAAGATGATCTTCTTGAGATCGTTTTGGTCTGCGCGTAATCTCTTGCTCTGAAAACGAAAAAACCGCCTTGCAGGGCGGTTTTTCGAAGGTTCTCTGAGCTACCAACTCTTTGAACCGAGGTAACTGGCTTGGAGGAGCGCAGTCACCAAAACTTGTCCTTTCAGTTTAGCCTTAACCGGCGCATGACTTCAAGACTAACTCCTCTAAATCAATTACCAGTGGCTGCTGCCAGTGGTGCTTTTGCATGTCTTTCCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGACTGAACGGGGGGTTCGTGCATACAGTCCAGCTTGGAGCGAACTGCCTACCCGGAACTGAGTGTCAGGCGTGGAATGAGACAAACGCGGCCATAACAGCGGAATGACACCGGTAAACCGAAAGGCAGGAACAGGAGAGCGCACGAGGGAGCCGCCAGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCACTGATTTGAGCGTCAGATTTCGTGATGCTTGTCAGGGGGGCGGAGCCTATGGAAAAACGGCTTTGCCGCGGCCCTCTCACTTCCCTGTTAAGTATCTTCCTGGCATCTTCCAGGAAATCTCCGCCCCGTTCGTAAGCCATTTCCGCTCGCCGCAGTCGAACGACCGAGCGTAGCGAGTCAGTGAGCGAGGAAGCGGAATATATCCTGTATCACATATTCTGCTGACGCACCGGTGCAGCCTTTTTTCTCCTGCCACATGAAGCACTTCACTGACACCCTCATCAGTGCCAACATAGTAAGCCAGTATACACTCCGCTAGCGCTGAGGTCTGCCTCGTGAAGAAGGTGTTGCTGACTCATACCAGGCCTGAATCGCCCCATCATCCAGCCAGAAAGTGAGGGAGCCACGGTTGATGAGAGCTTTGTTGTAGGTGGACCAGTTGGTGATTTTGAACTTTTGCTTTGCCACGGAACGGTCTGCGTTGTCGGGAAGATGCGTGATCTGATCCTTCAACTCAGCAAAAGTTCGATTTATTCAACAAAGCCACGTTGTGTCTCAAAATCTCTGATGTTACATTGCACAAGATAAAAATATATCATCATGAACAATAAAACTGTCTGCTTACATAAACAGTAATACAAGGGGTGTTTACTAGAGGTTGATCGGGCACGTAAGAGGTTCCAACTTTCACCATAATGAAATAAGATCACTACCGGGCGTATTTTTTGAGTTATCGAGATTTTCAGGAGCTAAGGAAGCTAAAATGGAGAAAAAAATCACGGGATATACCACCGTTGATATATCCCAATGGCATCGTAAAGAACATTTTGAGGCATTTCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTTTAAAGACCGTAAAGAAAAATAAGCACAAGTTTTATCCGGCCTTTATTCACATTCTTGCCCGCCTGATGAACGCTCACCCGGAGTTTCGTATGGCCATGAAAGACGGTGAGCTGGTGATCTGGGATAGTGTTCACCCTTGTTACACCGTTTTCCATGAGCAAACTGAAACGTTTTCGTCCCTCTGGAGTGAATACCACGACGATTTCCGGCAGTTTCTCCACATATATTCGCAAGATGTGGCGTGTTACGGTGAAAACCTGGCCTATTTCCCTAAAGGGTTTATTGAGAATATGTTTTTTGTCTCAGCCAATCCCTGGGTGAGTTTCACCAGTTTTGATTTAAACGTGGCCAATATGGACAACTTCTTCGCCCCCGTTTTCACGATGGGCAAATATTATACGCAAGGCGACAAGGTGCTGATGCCGCTGGCGATCCAGGTTCATCATGCCGTTTGTGATGGCTTCCATGTCGGCCGCATGCTTAATGAATTACAACAGTACTGTGATGAGTGGCAGGGCGGGGCGTAATAATACTAGCTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTTGCCACCTGACGTCTAAGAAAAGGAATATTCAGCAATTTGCCCGTGCCGAAGAAAGGCCCACCCGTGAAGGTGAGCCAGTGAGTTGATTGCTACGTAATTAGTTAGTTAGCCCTTAGTGACTCGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB3K3 — Kan resistance, medium (p15A ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb3k3
    "psb3k3": (
        "pSB3K3",
        "TACTAGTAGCGGCCGCTGCAGTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTATGCAGGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATCTCGAGTCCCGTCAAGTCAGCGTAATGCTCTGCCAGTGTTACAACCAATTAACCAATTCTGATTAGAAAAACTCATCGAGCATCAAATGAAACTGCAATTTATTCATATCAGGATTATCAATACCATATTTTTGAAAAAGCCGTTTCTGTAATGAAGGAGAAAACTCACCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATCGGTCTGCGATTCCGACTCGTCCAACATCAATACAACCTATTAATTTCCCCTCGTCAAAAATAAGGTTATCAAGTGAGAAATCACCATGAGTGACGACTGAATCCGGTGAGAATGGCAAAAGCTTATGCATTTCTTTCCAGACTTGTTCAACAGGCCAGCCATTACGCTCGTCATCAAAATCACTCGCATCAACCAAACCGTTATTCATTCGTGATTGCGCCTGAGCGAGACGAAATACGCGATCGCTGTTAAAAGGACAATTACAAACAGGAATCGAATGCAACCGGCGCAGGAACACTGCCAGCGCATCAACAATATTTTCACCTGAATCAGGATATTCTTCTAATACCTGGAATGCTGTTTTCCCGGGGATCGCAGTGGTGAGTAACCATGCATCATCAGGAGTACGGATAAAATGCTTGATGGTCGGAAGAGGCATAAATTCCGTCAGCCAGTTTAGTCTGACCATCTCATCTGTAACATCATTGGCAACGCTACCTTTGCCATGTTTCAGAAACAACTCTGGCGCATCGGGCTTCCCATACAATCGATAGATTGTCGCACCTGATTGCCCGACATTATCGCGAGCCCATTTATACCCATATAAATCAGCATCCATGTTGGAATTTAATCGCGGCCTCGAGCAAGACGTTTCCCGTTGAATATGGCTCATAACACCCCTTGTATTACTGTTTATGTAAGCAGACAGTTTTATTGTTCATGATGATATATTTTTATCTTGTGCAATGTAACATCAGAGATTTTGAGACACAACGTGGCTTTGTTGAATAAATCGAACTTTTGCTGAGTTGAAGGATCAGATCACGCATCTTCCCGACAACGCAGACCGTTCCGTGGCAAAGCAAAAGTTCAAAATCACCAACTGGTCCACCTACAACAAAGCTCTCATCAACCGTGGCTCCCTCACTTTCTGGCTGGATGATGGGGCGATTCAGGCCTGGTATGAGTCAGCAACACCTTCTTCACGAGGCAGACCTCAGCGCTAGCGGAGTGTATACTGGCTTACTATGTTGGCACTGATGAGGGTGTCAGTGAAGTGCTTCATGTGGCAGGAGAAAAAAGGCTGCACCGGTGCGTCAGCAGAATATGTGATACAGGATATATTCCGCTTCCTCGCTCACTGACTCGCTACGCTCGGTCGTTCGACTGCGGCGAGCGGAAATGGCTTACGAACGGGGCGGAGATTTCCTGGAAGATGCCAGGAAGATACTTAACAGGGAAGTGAGAGGGCCGCGGCAAAGCCGTTTTTCCATAGGCTCCGCCCCCCTGACAAGCATCACGAAATCTGACGCTCAAATCAGTGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCTGGCGGCTCCCTCGTGCGCTCTCCTGTTCCTGCCTTTCGGTTTACCGGTGTCATTCCGCTGTTATGGCCGCGTTTGTCTCATTCCACGCCTGACACTCAGTTCCGGGTAGGCAGTTCGCTCCAAGCTGGACTGTATGCACGAACCCCCCGTTCAGTCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGAAAGACATGCAAAAGCACCACTGGCAGCAGCCACTGGTAATTGATTTAGAGGAGTTAGTCTTGAAGTCATGCGCCGGTTAAGGCTAAACTGAAAGGACAAGTTTTGGTGACTGCGCTCCTCCAAGCCAGTTACCTCGGTTCAAAGAGTTGGTAGCTCAGAGAACCTTCGAAAAACCGCCCTGCAAGGCGGTTTTTTCGTTTTCAGAGCAAGAGATTACGCGCAGACCAAAACGATCTCAAGAAGATCATCTTATTAAGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTCCATGGTGCCACCTGACGTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCAGAATTTCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB3T5 — Tet resistance, medium (p15A ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb3t5
    "psb3t5": (
        "pSB3T5",
        "TACTAGTAGCGGCCGCTGCAGGAGTCACTAAGGGTTAGTTAGTTAGATTAGCAGAAAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTAAAACTTCCCTTGGGGTTATCATTGGGGCTCACTCAAAGGCGGTAATCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGCTAGAGATGGAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATAATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCTTAATAAGATGATCTTCTTGAGATCGTTTTGGTCTGCGCGTAATCTCTTGCTCTGAAAACGAAAAAACCGCCTTGCAGGGCGGTTTTTCGAAGGTTCTCTGAGCTACCAACTCTTTGAACCGAGGTAACTGGCTTGGAGGAGCGCAGTCACCAAAACTTGTCCTTTCAGTTTAGCCTTAACCGGCGCATGACTTCAAGACTAACTCCTCTAAATCAATTACCAGTGGCTGCTGCCAGTGGTGCTTTTGCATGTCTTTCCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGACTGAACGGGGGGTTCGTGCATACAGTCCAGCTTGGAGCGAACTGCCTACCCGGAACTGAGTGTCAGGCGTGGAATGAGACAAACGCGGCCATAACAGCGGAATGACACCGGTAAACCGAAAGGCAGGAACAGGAGAGCGCACGAGGGAGCCGCCAGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCACTGATTTGAGCGTCAGATTTCGTGATGCTTGTCAGGGGGGCGGAGCCTATGGAAAAACGGCTTTGCCGCGGCCCTCTCACTTCCCTGTTAAGTATCTTCCTGGCATCTTCCAGGAAATCTCCGCCCCGTTCGTAAGCCATTTCCGCTCGCCGCAGTCGAACGACCGAGCGTAGCGAGTCAGTGAGCGAGGAAGCGGAATATATCCTGTATCACATATTCTGCTGACGCACCGGTGCAGCCTTTTTTCTCCTGCCACATGAAGCACTTCACTGACACCCTCATCAGTGCCAACATAGTAAGCCAGTATACACTCCGCTAGCGCTGAGGTCTGCCTCGTGAAGAAGGTGTTGCTGACTCATACCAGGCCTGAATCGCCCCATCATCCAGCCAGAAAGTGAGGGAGCCACGGTTGATGAGAGCTTTGTTGTAGGTGGACCAGTTGGTGATTTTGAACTTTTGCTTTGCCACGGAACGGTCTGCGTTGTCGGGAAGATGCGTGATCTGATCCTTCAACTCAGCAAAAGTTCGATTTATTCAACAAAGCCACGTTGTGTCTCAAAATCTCTGATGTTACATTGCACAAGATAAAAATATATCATCATGAACAATAAAACTGTCTGCTTACATAAACAGTAATACAAGGGGTGTTTACTAGAGGAGATTCTCATGTTTGACAGCTTATCATCGATAAGCTTTAATGCGGTAGTTTATCACAGTTAAATTGCTAACGCAGTCAGGCACCGTGTATGAAATCTAACAATGCGCTCATCGTCATTCTCGGCACCGTCACCCTGGACGCTGTAGGCATAGGCTTGGTTATGCCGGTACTGCCGGGCCTCTTGCGGGATATCGTCCATTCCGACAGTATTGCCAGTCACTATGGCGTGCTGCTTGCGCTCTATGCGTTGATGCAATTTCTTTGCGCACCCGTTCTCGGAGCCCTGTCCGACCGCTTTGGCCGCCGTCCAGTCCTGCTCGCTTCGCTCCTTGGAGCCACTATCGACTACGCGATCATGGCGACCACACCCGTCCTGTGGATTCTCTACGCCGGACGCATCGTGGCGGGCATCACGGGTGCCACAGGTGCGGTTGCTGGTGCCTATATCGCCGACATCACCGATGGGGAAGATCGGGCTCGCCACTTCGGGCTCATGAGCGCTTGTTTCGGCGTGGGTATGGTGGCAGGCCCCGTGGCCGGGGGACTGTTGGGTGCCATCTCCTTGCATGCACCATTCCTTGCGGCGGCGGTGCTCAACGGCCTCAACCTCCTCCTGGGCTGCTTCCTTATGCAGGAATCGCATAAGGGAGAGCGCCGTCCGATGCCCTTGCGTGCCTTCAATCCAGTCAGCTCCTTCCGGTGGGCGCGGGGCATGACTATCGTCGCCGCACTTATGACTGTTTTCTTTATCATGCAACTCGTAGGACAGGTTCCGGCAGCGCTCTGGGTCATTTTCGGCGAGGACCGCTTTCGCTGGAGCGCGACGATGATCGGCCTGTCGCTTGCGGTATTCGGAATCTTGCACGCCCTCGCTCAAGCCTTCGTCACGGGCCCCGCCACCAAACGTTTCGGCGAGAAGCAGGCCATTATCGCGGGCATGGCGGCCGACGCGCTGGGCTACGTCTTGCTGGCGTTCGCGACGCGCGGCTGGATGGCCTTCCCCATTATGATTCTTCTCGCTTCCGGCGGCATCGGTATGCCCGCGTTGCAGGCCATGCTGTCCCGCCAAGTAGATGACGACCATCAGGGACAGCTTCAAGGGTCGCTCGCGGCTCTTACCAGCCTCACTTCGATCATTGGACCGCTGATCGTCACGGCGATTTATGCCGCCTCGGCGAGCACATGGAACGGGTTGGCATGGATTGTAGGTGCCGCCCTTTACCTTGTCTGCCTCCCCGCGTTGCGTCGCGGTGCATGGAGCCGGGCCACCTCGACCTAATAATACTAGCTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTTGCCACCTGACGTCTAAGAAAAGGAATATTCAGCAATTTGCCCGTGCCGAAGAAAGGCCCACCCGTGAAGGTGAGCCAGTGAGTTGATTGCTACGTAATTAGTTAGTTAGCCCTTAGTGACTCGAATTCGCGGCCGCTTCTAGAG",
    ),
    # pSB4C5 — Cm resistance, low (pSC101 ori). Real BioBrick assembly
    # vector, iGEM Registry. https://registry.igem.org/parts/psb4c5
    "psb4c5": (
        "pSB4C5",
        "TACTAGTAGCGGCCGCTGCAGGAGTCACTAAGGGTTAGTTAGTTAGATTAGCAGAAAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTAAAACTTCCCTTGGGGTTATCATTGGGGCTCACTCAAAGGCGGTAATCAGATAAAAAAAATCCTTAGCTTTCGCTAAGGATGATTTCTGCTAGAGCTGTCAGACCAAGTTTACGAGCTCGCTTGGACTCCTGTTGATAGATCCAGTAATGACCTCAGAACTCCATCTGGATTTGTTCAGAACGCTCGGTTGCCGCCGGGCGTTTTTTATTGGTGAGAATCCAAGCACTAGGGACAGTAAGACGGGTAAGCCTGTTGATGATACCGCTGCCTTACTGGGTGCATTAGCCAGTCTGAATGACCTGTCACGGGATAATCCGAAGTGGTCAGACTGGAAAATCAGAGGGCAGGAACTGCTGAACAGCAAAAAGTCAGATAGCACCACATAGCAGACCCGCCATAAAACGCCCTGAGAAGCCCGTGACGGGCTTTTCTTGTATTATGGGTAGTTTCCTTGCATGAATCCATAAAAGGCGCCTGTAGTGCCATTTACCCCCATTCACTGCCAGAGCCGTGAGCGCAGCGAACTGAATGTCACGAAAAAGACAGCGACTCAGGTGCCTGATGGTCGGAGACAAAAGGAATATTCAGCGATTTGCCCGAGCTTGCGAGGGTGCTACTTAAGCCTTTAGGGTTTTAAGGTCTGTTTTGTAGAGGAGCAAACAGCGTTTGCGACATCCTTTTGTAATACTGCGGAACTGACTAAAGTAGTGAGTTATACACAGGGCTGGGATCTATTCTTTTTATCTTTTTTTATTCTTTCTTTATTCTATAAATTATAACCACTTGAATATAAACAAAAAAAACACACAAAGGTCTAGCGGAATTTACAGAGGGTCTAGCAGAATTTACAAGTTTTCCAGCAAAGGTCTAGCAGAATTTACAGATACCCACAACTCAAAGGAAAAGGACATGTAATTATCATTGACTAGCCCATCTCAATTGGTATAGTGATTAAAATCACCTAGACCAATTGAGATGTATGTCTGAATTAGTTGTTTTCAAAGCAAATGAACTAGCGATTAGTCGCTATGACTTAACGGAGCATGAAACCAAGCTAATTTTATGCTGTGTGGCACTACTCAACCCCACGATTGAAAACCCTACAAGGAAAGAACGGACGGTATCGTTCACTTATAACCAATACGCTCAGATGATGAACATCAGTAGGGAAAATGCTTATGGTGTATTAGCTAAAGCAACCAGAGAGCTGATGACGAGAACTGTGGAAATCAGGAATCCTTTGGTTAAAGGCTTTGAGATTTTCCAGTGGACAAACTATGCCAAGTTCTCAAGCGAAAAATTAGAATTAGTTTTTAGTGAAGAGATATTGCCTTATCTTTTCCAGTTAAAAAAATTCATAAAATATAATCTGGAACATGTTAAGTCTTTTGAAAACAAATACTCTATGAGGATTTATGAGTGGTTATTAAAAGAACTAACACAAAAGAAAACTCACAAGGCAAATATAGAGATTAGCCTTGATGAATTTAAGTTCATGTTAATGCTTGAAAATAACTACCATGAGTTTAAAAGGCTTAACCAATGGGTTTTGAAACCAATAAGTAAAGATTTAAACACTTACAGCAATATGAAATTGGTGGTTGATAAGCGAGGCCGCCCGACTGATACGTTGATTTTCCAAGTTGAACTAGATAGACAAATGGATCTCGTAACCGAACTTGAGAACAACCAGATAAAAATGAATGGTGACAAAATACCAACAACCATTACATCAGATTCCTACCTACATAACGGACTAAGAAAAACACTACACGATGCTTTAACTGCAAAAATTCAGCTCACCAGTTTTGAGGCAAAATTTTTGAGTGACATGCAAAGTAAGTATGATCTCAATGGTTCGTTCTCATGGCTCACGCAAAAACAACGAACCACACTAGAGAACATACTGGCTAAATACGGAAGGATCTGAGGTTCTTATGGCTCTTGTATCTATCAGTGAAGCATCAAGACTAACAAACAAAAGTAGAACAACTGTTCACCGTTACATATCAAAGGGAAAACTGTCCATATGCACAGATGAAAACGGTGTAAAAAAGATAGATACATCAGAGCTTTTACGAGTTTTTGGTGCATTCAAAGCTGTTCACCATGAACAGATCGACAATGTAACTACTAGAGGTTGATCGGGCACGTAAGAGGTTCCAACTTTCACCATAATGAAATAAGATCACTACCGGGCGTATTTTTTGAGTTATCGAGATTTTCAGGAGCTAAGGAAGCTAAAATGGAGAAAAAAATCACGGGATATACCACCGTTGATATATCCCAATGGCATCGTAAAGAACATTTTGAGGCATTTCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTTTAAAGACCGTAAAGAAAAATAAGCACAAGTTTTATCCGGCCTTTATTCACATTCTTGCCCGCCTGATGAACGCTCACCCGGAGTTTCGTATGGCCATGAAAGACGGTGAGCTGGTGATCTGGGATAGTGTTCACCCTTGTTACACCGTTTTCCATGAGCAAACTGAAACGTTTTCGTCCCTCTGGAGTGAATACCACGACGATTTCCGGCAGTTTCTCCACATATATTCGCAAGATGTGGCGTGTTACGGTGAAAACCTGGCCTATTTCCCTAAAGGGTTTATTGAGAATATGTTTTTTGTCTCAGCCAATCCCTGGGTGAGTTTCACCAGTTTTGATTTAAACGTGGCCAATATGGACAACTTCTTCGCCCCCGTTTTCACGATGGGCAAATATTATACGCAAGGCGACAAGGTGCTGATGCCGCTGGCGATCCAGGTTCATCATGCCGTTTGTGATGGCTTCCATGTCGGCCGCATGCTTAATGAATTACAACAGTACTGTGATGAGTGGCAGGGCGGGGCGTAATAATACTAGCTCCGGCAAAAAAACGGGCAAGGTGTCACCACCCTGCCCTTTTTCTTTAAAACCGAAAAGATTACTTCGCGTTTGCCACCTGACGTCTAAGAAAAGGAATATTCAGCAATTTGCCCGTGCCGAAGAAAGGCCCACCCGTGAAGGTGAGCCAGTGAGTTGATTGCTACGTAATTAGTTAGTTAGCCCTTAGTGACTCGAATTCGCGGCCGCTTCTAGAG",
    ),
}


def validate_payload_cds(name: str, sequence: str) -> str:
    """Validate a payload coding sequence and return it as uppercase DNA.

    Reuses ``AntisenseNotGate.__init__``'s own payload validation — ``to_rna``,
    ``is_valid_rna``, starts with a start codon — rather than inventing a second
    definition of "a valid payload" (CLAUDE.md §1), plus the checks a full CDS needs
    that a single-gate constructor does not: whole codons, and no in-frame stop before
    the true end.

    A trailing run of stop codons is accepted as *one* stop, not rejected as several
    premature ones — real parts carry them. BBa_E0040 ends ``...UAC AAA UAA UAA``, two
    tandem stops, a common belt-and-braces pattern against ribosomal readthrough.
    """
    if not isinstance(sequence, str):
        raise InputValidationError(f"{name}: payload CDS must be a sequence string.")
    rna = sq.to_rna(sequence)
    if len(rna) > 2000:
        raise InputValidationError(
            f"{name}: payload exceeds the 2,000-nt thermodynamic compute limit."
        )
    if not sq.is_valid_rna(rna):
        raise InputValidationError(f"Payload {name!r} is not a valid RNA or DNA sequence.")
    if rna[:3] != sq.START_CODON:
        raise InputValidationError(
            f"Payload {name!r} must be a full CDS starting with a start codon, got {rna[:3]!r}."
        )
    if len(rna) % 3 != 0:
        raise InputValidationError(f"Payload {name!r} is not a whole number of codons.")

    stops = set(sq.find_stops(rna))
    n = len(rna)
    trailing = 0
    while n - 3 * (trailing + 1) in stops:
        trailing += 1
    if trailing == 0:
        raise InputValidationError(f"Payload {name!r} does not end in a stop codon.")
    if len(stops) != trailing:
        raise InputValidationError(
            f"Payload {name!r} has a premature in-frame stop codon before its end."
        )

    return sq.to_dna(rna)


def _lookup_part(table: dict, key, label: str) -> tuple[str, str]:
    try:
        return table[key]
    except KeyError:
        wanted = getattr(key, "value", key)
        configured = ", ".join(getattr(k, "value", str(k)) for k in table) or "none"
        raise InputValidationError(
            f"No {label} is configured for {wanted!r} yet (docs/ROADMAP.md Q11/Q12/Q13). "
            f"Configured: {configured}."
        ) from None


def validate_backbone_insertion(backbone: tuple[Segment, ...], insertion: int) -> None:
    """Reject insertion through known local functional feature intervals."""
    offset = 0
    for segment in backbone:
        for raw in segment.annotations:
            feature = json.loads(raw)
            if feature["type"] in {
                "CDS",
                "gene",
                "rep_origin",
                "promoter",
                "regulatory",
                "terminator",
            }:
                for start, end, _strand in feature["parts"]:
                    if start + offset < insertion < end + offset:
                        raise InputValidationError(
                            f"Insertion disrupts backbone {feature['type']} "
                            f"at {start + offset}:{end + offset}."
                        )
        offset += segment.length_bp


class PlasmidBuilder:
    """Assembles a circuit onto a backbone and checks it can be built.

    Args:
        screener: Shared ``MotifScreener``. Must be configured with the same standard
            passed below, or the check and the claim disagree.
        codons: Shared ``CodonOptimizer``. Held for the payload-rewriting step named in
            ``payload_segment``; not called by this implementation (see the module
            docstring's "No codon optimisation" note).
        standard: The assembly standard to enforce. RFC10 forbids EcoRI, XbaI, SpeI,
            PstI and NotI inside a part; RFC1000 (Type IIS) forbids BsaI and SapI.
        backbone: Fixed segments every construct shares — origin of replication,
            selection marker for the plasmid itself, and so on. Distinct from the
            circuit's payload.
    """

    def __init__(
        self,
        screener: MotifScreener,
        codons: CodonOptimizer,
        standard: AssemblyStandard = AssemblyStandard.RFC10,
        backbone: tuple[Segment, ...] = (),
        *,
        insertion_index: int = 0,
        optimize_codons: bool = False,
    ) -> None:
        self.screener = screener
        self.codons = codons
        self.standard = standard
        self.backbone = backbone
        if (
            isinstance(insertion_index, bool)
            or not isinstance(insertion_index, int)
            or not 0 <= insertion_index <= sum(s.length_bp for s in backbone)
        ):
            raise InputValidationError(
                "backbone.insertion_index must be a 0-based boundary within the vector."
            )
        validate_backbone_insertion(backbone, insertion_index)
        self.insertion_index = insertion_index
        self.optimize_codons = optimize_codons
        self._optimized_payloads: dict[str, tuple[Segment, str]] = {}

    def build(
        self,
        circuit: CircuitCandidate,
        outcome: DesiredOutcome,
        *,
        custom_payload: str | None = None,
    ) -> PlasmidDesign:
        """Lay out one circuit as an orderable construct.

        Args:
            circuit: A ranked circuit from stage 4, with its switch designs.
            outcome: What the circuit should express when it fires.
            custom_payload: The raw CDS from ``params["payload"]["custom_sequence"]``,
                required when (and only meaningful when) ``outcome`` is
                ``DesiredOutcome.CUSTOM`` — the one outcome ``payload_segment`` cannot
                resolve from the catalog itself, since a custom sequence has no catalog
                entry to look up. Validated through the same
                :func:`validate_payload_cds` every catalog entry passes through.

        Returns:
            ``PlasmidDesign`` with its segments, full sequence, and any standard
            violations. **Violations are recorded, not silently repaired** — a
            researcher needs to know the construct they are about to order has a
            problem, and quietly mutating their design is worse than reporting it.

        Raises:
            InputValidationError: The circuit has no switch designs, no promoter or
                terminator is configured for the requested host yet, ``outcome`` needs
                the catalog and has no entry there, or ``outcome`` is ``CUSTOM`` with
                no (or an invalid) ``custom_payload`` (docs/ROADMAP.md Q11/Q12/Q13) —
                never a silently incomplete plasmid.
        """
        if not circuit.designs:
            raise InputValidationError(
                "A circuit needs at least one switch design to build a plasmid."
            )

        # Only an identity expression with one activating input has a compiled
        # topology here. Concatenation cannot implement a Boolean operator.
        if len(circuit.designs) != 1 or circuit.expression.operator is not LogicOperator.IDENTITY:
            raise InputValidationError(
                "Unsupported physical circuit: no reviewed Boolean compiler."
            )
        physical_design = circuit.designs[0]
        inputs = physical_design.trigger_set.activators
        if physical_design.gate_kind is not GateKind.TOEHOLD or len(inputs) != 1:
            raise InputValidationError(
                "Unsupported physical gate: no reviewed compiler for this mechanism."
            )
        allowed_ids = {inputs[0].gene_id, inputs[0].symbol}
        if set(circuit.expression.gene_ids()) - allowed_ids:
            raise InputValidationError(
                "Logical expression does not identify the physical gate input."
            )
        if circuit.designs[0].trigger_set.repressors:
            raise InputValidationError(
                "Unsupported physical inversion: this builder compiles activating gates only."
            )
        host = circuit.designs[0].host
        if host is not Host.ECOLI and any(
            (segment.name, segment.sequence) in BACKBONES.values() for segment in self.backbone
        ):
            raise InputValidationError("Catalog vectors are currently supported only for E. coli.")
        if outcome in PAYLOAD_HOSTS and host not in PAYLOAD_HOSTS[outcome]:
            raise InputValidationError(f"Payload {outcome.value!r} has E. coli-only host scope.")
        promoter_name, promoter_seq = _lookup_part(PROMOTERS, host, "promoter")
        terminator_name, terminator_seq = _lookup_part(TERMINATORS, host, "terminator")

        if outcome is DesiredOutcome.CUSTOM:
            if not custom_payload:
                raise InputValidationError(
                    "DesiredOutcome.CUSTOM needs params['payload']['custom_sequence']."
                )
            payload = Segment(
                SegmentKind.PAYLOAD, "Custom", validate_payload_cds("Custom", custom_payload)
            )
        else:
            payload = self.payload_segment(outcome)

        optimization = ""
        if self.optimize_codons:
            original = payload.sequence
            if original not in self._optimized_payloads:
                rejected = []
                variants = self.codons.variants(
                    original,
                    count=1,
                    avoid_enzymes=tuple(
                        name for name in self.screener.sites if not name.endswith("_rc")
                    ),
                    acceptable=self.screener.is_compliant,
                    on_rejected=lambda _sequence, reasons: rejected.extend(reasons),
                )
                clean = next((variant for variant in variants if variant.clean), None)
                if clean is None:
                    raise InputValidationError(
                        "No clean synonymous payload variant: " + "; ".join(rejected)
                    )
                provenance = json.dumps(
                    {
                        "status": "synonymous_variant_selected",
                        "original_sha256": hashlib.sha256(original.encode()).hexdigest(),
                        "optimized_sha256": hashlib.sha256(
                            sq.to_dna(clean.sequence).encode()
                        ).hexdigest(),
                        "codons_changed": clean.codons_changed,
                        "seed": clean.seed,
                        "translation_score": clean.translation_score,
                        "unresolved": list(clean.unresolved),
                        "host": host.value,
                        "protein_preserved": True,
                    },
                    sort_keys=True,
                    allow_nan=False,
                )
                self._optimized_payloads[original] = (
                    Segment(
                        payload.kind,
                        payload.name,
                        validate_payload_cds(payload.name, clean.sequence),
                    ),
                    provenance,
                )
            payload, optimization = self._optimized_payloads[original]

        design = circuit.designs[0]
        aug = design.architecture.get("aug_index")
        if aug is not None:
            # The switch supplies initiation AUG; append the downstream payload CDS
            # once. If a payload head was already modelled, consume that exact head.
            head = design.architecture.get("payload_head_length", 0)
            expected = sq.to_rna(payload.sequence)[3 : 3 + head]
            if head and not design.sequence.endswith(expected):
                raise InputValidationError(
                    "Embedded payload head does not match the requested CDS."
                )
            payload = Segment(payload.kind, payload.name, payload.sequence[3 + head :])

        segments: list[Segment] = []
        for design in circuit.designs:
            # Promoter, then switch — one pair per switch, since a multi-input circuit
            # needs its own regulation per unit (docs/plasmids.md §8, the multi-switch
            # layout question). The switch itself does the regulating; the promoter is
            # deliberately constitutive, or a regulated one on top would confound the
            # logic the switch already encodes.
            segments.append(Segment(SegmentKind.PROMOTER, promoter_name, promoter_seq))
            segments.append(
                Segment(SegmentKind.SWITCH, design.design_id, sq.to_dna(design.sequence))
            )
        # Payload, in frame with the last switch's start codon — the join checked below.
        segments.append(payload)
        segments.append(Segment(SegmentKind.TERMINATOR, terminator_name, terminator_seq))
        cassette_length = sum(segment.length_bp for segment in segments)
        insertion_index = self.insertion_index if self.backbone else 0
        transformed_annotations = []
        source_offset = 0
        for segment in self.backbone:
            for annotation in segment.annotations:
                feature = json.loads(annotation)
                transformed_parts = []
                for start, end, strand in feature["parts"]:
                    start, end = start + source_offset, end + source_offset
                    if start < insertion_index < end:
                        transformed_parts.extend(
                            [
                                [start, insertion_index, strand],
                                [insertion_index + cassette_length, end + cassette_length, strand],
                            ]
                        )
                    else:
                        transformed_parts.append(
                            [
                                start + (cassette_length if start >= insertion_index else 0),
                                end + (cassette_length if start >= insertion_index else 0),
                                strand,
                            ]
                        )
                feature["parts"] = transformed_parts
                if len(transformed_parts) > 1 and not feature.get("operator"):
                    feature["operator"] = "join"
                transformed_annotations.append(json.dumps(feature, sort_keys=True))
            source_offset += segment.length_bp
        if self.backbone:
            prefix: list[Segment] = []
            suffix: list[Segment] = []
            remaining = insertion_index
            for segment in self.backbone:
                split = min(remaining, segment.length_bp)
                if split:
                    prefix.append(Segment(segment.kind, segment.name, segment.sequence[:split]))
                if split < segment.length_bp:
                    suffix.append(Segment(segment.kind, segment.name, segment.sequence[split:]))
                remaining -= split
            segments = [*prefix, *segments, *suffix]
        plasmid = Plasmid(tuple(segments))

        motif_findings = self.screener.violations(plasmid.sequence, circular=bool(self.backbone))
        violations = [str(v) for v in motif_findings]
        frames = _frame_violations(circuit.designs, payload)
        violations.extend(frames)
        backbone_ranges = []
        offset = 0
        for segment in segments:
            if segment.kind is SegmentKind.BACKBONE:
                backbone_ranges.append((offset, offset + segment.length_bp))
            offset += segment.length_bp
        eligible = list(frames)
        for finding in motif_findings:
            preexisting = any(
                start <= finding.start and finding.start + len(finding.motif) <= end
                for start, end in backbone_ranges
            )
            if finding.kind == "forbidden motif" or (
                finding.kind == "restriction site" and not preexisting
            ):
                eligible.append(str(finding))
        # Full-construct homopolymers and pre-existing vector restriction sites remain
        # visible assembly caveats. They do not establish a nonfunctional ORF.
        coding_regions = ()
        if aug is not None:
            start = insertion_index + len(promoter_seq) + aug
            end = insertion_index + len(promoter_seq) + len(design.sequence) + payload.length_bp
            protein = sq.translate(sq.to_rna(plasmid.sequence[start:end]))
            coding_regions = ((start, end, payload.name + " N-terminal fusion", protein),)

        return PlasmidDesign(
            plasmid_id=f"plasmid-{circuit.circuit_id.rsplit('-', 1)[-1]}-{outcome.value}",
            circuit_id=circuit.circuit_id,
            plasmid=plasmid,
            standard=self.standard,
            violations=tuple(violations),
            coding_regions=coding_regions,
            eligibility_violations=tuple(eligible),
            payload_optimization=optimization,
            backbone_annotations=tuple(transformed_annotations),
            insertion_index=insertion_index if self.backbone else None,
            assembly_method="sequence_insertion" if self.backbone else "expression_cassette",
            assembly_notes=(
                (
                    "Sequence insertion defines coordinates only; a validated cloning "
                    "protocol and overlaps/enzyme cuts are not supplied.",
                )
                if self.backbone
                else ()
            ),
        )

    def payload_segment(self, outcome: DesiredOutcome) -> Segment:
        """The coding sequence for the chosen output.

        Args:
            outcome: GFP, mCherry, Luciferase, antibiotic resistance, apoptosis
                inducer. Never ``DesiredOutcome.CUSTOM`` — a custom sequence has no
                catalog entry to look up; the caller builds its ``Segment`` directly
                from ``params["payload"]["custom_sequence"]``, through
                :func:`validate_payload_cds`, the same validation this method applies
                to every table entry.

        Returns:
            A ``Segment`` of kind ``PAYLOAD``.

        Raises:
            InputValidationError: ``outcome`` is ``CUSTOM``, or no payload is
                configured for it yet (docs/ROADMAP.md Q11).

        Note:
            **Every output is equivalent.** A reporter and a selective marker are the
            same kind of construct with a different payload — there is no structural
            difference, and the earlier version of this engine emitted a separate
            ``marker`` segment which made markers look like second-class add-ons. They
            are not: when a marker is selected, it *is* the payload.
        """
        if outcome is DesiredOutcome.CUSTOM:
            raise InputValidationError(
                "DesiredOutcome.CUSTOM has no catalog entry — build its Segment from "
                "params['payload']['custom_sequence'] via validate_payload_cds directly."
            )
        name, cds = _lookup_part(PAYLOADS, outcome, "payload")
        return Segment(SegmentKind.PAYLOAD, name, validate_payload_cds(name, cds))


def _frame_violations(designs: tuple[GateDesign, ...], payload: Segment) -> list[str]:
    """Reading-frame continuity from each switch's own start codon through the
    payload — the join the docstring above calls out, and the one gotcha that
    assembles clean, screens clean, prices normally, and expresses nothing
    (docs/plasmids.md §7.4).

    ``architecture["aug_index"]`` is the toehold family's own record of where its
    start codon sits (``gates/toehold.py`` — read, not recomputed, per CLAUDE.md §5); a
    design from a family that does not record one has nothing to check here.
    """
    violations: list[str] = []
    payload_dna = payload.sequence

    for design in designs:
        aug_index = design.architecture.get("aug_index")
        if aug_index is None:
            continue

        tail = sq.to_rna(design.sequence)[aug_index:]
        fused = sq.to_rna(tail + payload_dna)

        if len(fused) % 3 != 0:
            violations.append(
                f"{design.design_id}: the switch's start codon is not in frame with "
                f"the payload ({len(fused)} nt from the start codon is not a whole "
                "number of codons)."
            )
            continue

        stops = set(sq.find_stops(fused))
        n = len(fused)
        trailing = 0
        while n - 3 * (trailing + 1) in stops:
            trailing += 1
        premature = sorted(position for position in stops if position < n - 3 * trailing)
        if premature:
            violations.append(
                f"{design.design_id}: a premature in-frame stop codon at position "
                f"{premature[0]} of the fused switch+payload truncates translation "
                "before the payload."
            )

    return violations


def parse_custom_backbone(genbank_text: str) -> Segment:
    """Parse a researcher-supplied backbone from raw GenBank text (docs/plasmids.md
    Q13, docs/ROADMAP.md E5b) — the second and last function in this module that
    touches Biopython (ADR 0007), confined here for the same reason ``to_genbank`` is:
    a ``SeqRecord`` is built and discarded, never crossing back into engine or
    Platform code.

    Args:
        genbank_text: The uploaded file's raw text content.

    Returns:
        One BACKBONE segment containing uppercase DNA and immutable serialized
        local feature coordinates, strands, compound operators and qualifiers.
        Fuzzy and remote positions are rejected; coordinates are shifted when the
        compiled cassette is inserted. Parsing supplies no host-functional or cloning
        protocol certification.

    Raises:
        InputValidationError: the text does not parse as GenBank, the record is not
            circular (docs/plasmids.md §7.5 — a GenBank round-trip can silently lose
            topology; a plasmid backbone that is not circular is not a plasmid
            backbone), or its sequence is not valid DNA/RNA.
    """
    try:
        record = SeqIO.read(io.StringIO(genbank_text), "genbank")
    except Exception as exc:
        raise InputValidationError(f"Could not parse the uploaded file as GenBank: {exc}") from None

    if record.annotations.get("topology") != "circular":
        raise InputValidationError(
            "The uploaded backbone is not annotated as circular in its LOCUS line — "
            "a linear file cannot be a plasmid backbone (docs/plasmids.md §7.5)."
        )

    rna = sq.to_rna(str(record.seq))
    if not rna or not sq.is_valid_rna(rna):
        raise InputValidationError("The uploaded backbone has no valid DNA/RNA sequence.")

    annotations = []
    for feature in record.features:
        if feature.location is None:
            raise InputValidationError("Backbone annotations require known feature locations.")
        parts = []
        for location in feature.location.parts:
            if (
                not isinstance(location.start, ExactPosition)
                or not isinstance(location.end, ExactPosition)
                or location.ref
            ):
                raise InputValidationError("Backbone annotations require exact local coordinates.")
            start, end = int(location.start), int(location.end)
            if not 0 <= start < end <= len(rna):
                raise InputValidationError("Backbone annotation is outside the supplied sequence.")
            parts.append([start, end, location.strand])
        annotations.append(
            json.dumps(
                {
                    "type": feature.type,
                    "parts": parts,
                    "operator": getattr(feature.location, "operator", None),
                    "qualifiers": feature.qualifiers,
                },
                sort_keys=True,
            )
        )
    name = record.name or record.id or "Custom"
    return Segment(SegmentKind.BACKBONE, name, sq.to_dna(rna), annotations=tuple(annotations))


#: GenBank feature type per segment kind. Standard keys only (CLAUDE.md §7's own
#: instruction, echoed in docs/plasmids.md §6 P4) — CERNAL-specific metadata goes in
#: qualifiers, never in an invented feature type.
_GENBANK_FEATURE_TYPE: dict[SegmentKind, str] = {
    SegmentKind.PROMOTER: "promoter",
    SegmentKind.SWITCH: "misc_feature",
    SegmentKind.PAYLOAD: "CDS",
    SegmentKind.TERMINATOR: "terminator",
    SegmentKind.BACKBONE: "misc_feature",
}


def to_genbank(design: PlasmidDesign) -> bytes:
    """Render a ``PlasmidDesign`` as an annotated circular GenBank file.

    The only place in this module that imports Biopython (ADR 0007). A ``SeqRecord``
    is constructed and discarded here; it never crosses back into engine or Platform
    code. Every CERNAL-produced segment becomes a feature with a standard GenBank type
    (docs/plasmids.md §6 P4) — the switch and any preserved backbone segments as
    ``misc_feature``, the payload as ``CDS`` — carrying CERNAL's own identifiers as
    qualifiers rather than inventing a nonstandard feature key.
    """
    record = SeqRecord(
        Seq(design.plasmid.sequence),
        id=design.plasmid_id,
        name=design.plasmid_id[:20],
        description=f"CERNAL computationally assembled construct {design.plasmid_id}",
    )
    record.annotations["molecule_type"] = "DNA"
    record.annotations["topology"] = (
        "circular"
        if any(s.kind is SegmentKind.BACKBONE for s in design.plasmid.segments)
        else "linear"
    )

    position = 0
    for segment in design.plasmid.segments:
        end = position + segment.length_bp
        record.features.append(
            SeqFeature(
                SimpleLocation(position, end, strand=1),
                type=(
                    "misc_feature"
                    if segment.kind is SegmentKind.PAYLOAD and design.coding_regions
                    else _GENBANK_FEATURE_TYPE.get(segment.kind, "misc_feature")
                ),
                qualifiers={
                    "label": [segment.name],
                    "cernal_role": [segment.kind.value],
                    "cernal_plasmid_id": [design.plasmid_id],
                    "cernal_circuit_id": [design.circuit_id],
                    "note": [
                        "Generated by CERNAL — computationally assembled, not "
                        "wet-lab validated (docs/plasmids.md §9)."
                    ],
                },
            )
        )
        position = end

    for start, end, name, protein in design.coding_regions:
        record.features.append(
            SeqFeature(
                SimpleLocation(start, end, strand=1),
                type="CDS",
                qualifiers={
                    "label": [name],
                    "translation": [protein.rstrip("*")],
                    "codon_start": ["1"],
                    "note": ["Switch-initiated N-terminal fusion; computationally assembled."],
                },
            )
        )
    for annotation in design.backbone_annotations:
        feature = json.loads(annotation)
        parts = [
            SimpleLocation(start, end, strand=strand) for start, end, strand in feature["parts"]
        ]
        location = (
            parts[0]
            if len(parts) == 1
            else CompoundLocation(parts, operator=feature.get("operator") or "join")
        )
        record.features.append(
            SeqFeature(location, type=feature["type"], qualifiers=feature["qualifiers"])
        )
    return record.format("genbank").encode("utf-8")


# --- SBOL 3 export (ADR 0008) -------------------------------------------------------

#: Bundled iGEM Registry metadata, written by ``tools/sync_registry_parts.py``. Identity
#: and provenance only — never sequences; the tables above stay the single source of
#: truth for what CERNAL builds (CLAUDE.md §1).
_REGISTRY_CATALOG_PATH = Path(__file__).resolve().parent.parent / "data" / "registry" / "parts.json"

#: Sequence Ontology role per segment kind, for a part with no Registry entry of its own.
#: The switch is the case that matters: it is designed by CERNAL for this run and exists
#: in no registry, so it gets ``engineered_region`` rather than being mislabelled as a
#: catalogued part. Standard SO terms only, the same rule ``_GENBANK_FEATURE_TYPE``
#: follows for GenBank feature keys.
_SBOL_ROLE: dict[SegmentKind, str] = {
    SegmentKind.PROMOTER: "SO:0000167",  # promoter
    SegmentKind.SWITCH: "SO:0000804",  # engineered_region
    SegmentKind.PAYLOAD: "SO:0000316",  # CDS
    SegmentKind.TERMINATOR: "SO:0000141",  # terminator
    SegmentKind.BACKBONE: "SO:0000755",  # plasmid_vector
}

#: Namespace for every identity CERNAL mints. Fixed, not derived from a hostname or a
#: run id: an SBOL identity that moved with the deployment would make two exports of the
#: same design non-identical, and ``write_artifact`` checksums what this function returns.
SBOL_NAMESPACE = "https://cernal.igem.org/2026"

#: The ontology prefixes this module is prepared to turn into a URI. The Registry serves
#: a few parts with an ``IGEM:`` role — BBa_K124002's ``IGEM:0000006`` is one — which is
#: not a Sequence Ontology term and must not be emitted as though it were. Those fall
#: back to the kind-based SO role, which is a true statement about the part's function
#: rather than a fabricated accession.
_ONTOLOGY_URI = {"SO": "https://identifiers.org/SO:{accession}"}


@cache
def load_registry_catalog() -> dict[str, dict]:
    """The bundled Registry metadata, keyed by local part name. Empty if never synced.

    Cached per process: a small JSON file that cannot change between requests. Missing
    is not an error — SBOL export still works, it just falls back to the kind-based SO
    role and emits no Registry provenance.
    """
    if not _REGISTRY_CATALOG_PATH.is_file():
        return {}
    return json.loads(_REGISTRY_CATALOG_PATH.read_text(encoding="utf-8"))


@cache
def load_part_catalog() -> dict[str, dict]:
    """Registry plus separately pinned primary GenBank CDS metadata."""
    external = Path(__file__).resolve().parents[1] / "data" / "marker_sources.json"
    return {**load_registry_catalog(), **json.loads(external.read_text(encoding="utf-8"))}


def _role_uri(segment: Segment, entry: dict | None) -> str:
    """The SO role URI for one segment, preferring the Registry's own accession."""
    accession = (entry or {}).get("role_accession", "")
    prefix, _, number = accession.partition(":")
    if prefix in _ONTOLOGY_URI and number:
        return _ONTOLOGY_URI[prefix].format(accession=accession)
    return _ONTOLOGY_URI["SO"].format(accession=_SBOL_ROLE[segment.kind])


def _safe_id(text: str) -> str:
    """``text`` as a legal SBOL display id.

    SBOL requires alphanumeric-or-underscore and forbids a leading digit. Every CERNAL
    identifier is otherwise illegal here: ``plas-000001``, ``circ-000001`` and the
    gate-designed segment names all carry a hyphen, and a part name may start with a
    digit. Normalising is not cosmetic — ``sbol3`` raises on an invalid display id, so
    an unnormalised id fails the export outright rather than producing a bad file.
    """
    safe = "".join(character if character.isalnum() else "_" for character in text)
    return f"_{safe}" if safe and safe[0].isdigit() else safe


def _display_id(segment: Segment, index: int) -> str:
    """A stable, SBOL-legal display id for one segment.

    The positional index keeps two segments of the same part distinct without a counter
    or a uuid, and keeps the id stable for a given design.
    """
    return f"s{index}_{_safe_id(segment.name)}"


def to_sbol3(design: PlasmidDesign) -> bytes:
    """Render a ``PlasmidDesign`` as an SBOL 3 document (sorted N-Triples).

    The only place in this module that imports ``sbol3`` (ADR 0008), following the same
    containment rule ``to_genbank`` follows for Biopython: a ``Document`` is built and
    discarded here and never crosses back into engine or Platform code.

    Answers iGEM's "compatible with, and does it leverage, existing synthetic biology
    standards" by emitting the construct in the standard the question names, with each
    segment carrying a real Sequence Ontology role and — where the part came from the
    iGEM Registry — that part's own accession and URL as provenance.

    **Byte-identical across runs**, which ``write_artifact``'s SHA-256 depends on and
    CLAUDE.md §6 requires: identities are derived from the design, serialization is
    ``SORTED_NTRIPLES``, and nothing here reads a clock or generates a uuid.

    Args:
        design: The assembled construct to export.

    Returns:
        The SBOL 3 document as UTF-8 encoded sorted N-Triples.
    """
    catalog = load_part_catalog()
    sbol3.set_namespace(SBOL_NAMESPACE)
    document = sbol3.Document()

    sequence = sbol3.Sequence(
        f"{_safe_id(design.plasmid_id)}_sequence",
        elements=design.plasmid.sequence,
        encoding=sbol3.IUPAC_DNA_ENCODING,
    )
    construct = sbol3.Component(
        _safe_id(design.plasmid_id),
        sbol3.SBO_DNA,
        roles=[
            _ONTOLOGY_URI["SO"].format(
                accession=(
                    "SO:0000755"
                    if any(s.kind is SegmentKind.BACKBONE for s in design.plasmid.segments)
                    else "SO:0000804"
                )
            )
        ],
        sequences=[sequence],
        name=design.plasmid_id,
        description=(
            f"CERNAL computationally assembled construct {design.plasmid_id} "
            f"for circuit {design.circuit_id}, assembly setting {design.standard.value}; "
            f"{len(design.violations)} recorded violation(s). "
            "Computationally assembled, not wet-lab validated (docs/plasmids.md §9)."
        ),
    )
    document.add(sequence)

    position = 0
    for index, segment in enumerate(design.plasmid.segments):
        entry = catalog.get(segment.name)
        part = sbol3.Component(
            _display_id(segment, index),
            sbol3.SBO_DNA,
            roles=[_role_uri(segment, entry)],
            name=segment.name,
        )
        if entry:
            # Provenance, not a second copy of the part: the Registry's own identifier
            # for the thing this segment is, so a reader can go and look it up.
            part.description = (
                f"Primary-source part {entry.get('registry_name', entry.get('accession'))} "
                f"— {entry['url']}"
            )
            part.derived_from = [entry["url"]]

        feature = sbol3.SubComponent(part)
        # SBOL Range is 1-based inclusive on both ends; CERNAL coordinates are 0-indexed
        # with an exclusive end (CLAUDE.md §6), so start shifts by one and end does not.
        feature.locations = [sbol3.Range(sequence, position + 1, position + segment.length_bp)]
        construct.features.append(feature)
        document.add(part)
        position += segment.length_bp

    for start, end, name, _protein in design.coding_regions:
        coding = sbol3.SequenceFeature(
            locations=[sbol3.Range(sequence, start + 1, end)],
            roles=[_ONTOLOGY_URI["SO"].format(accession="SO:0000316")],
            name=name,
        )
        construct.features.append(coding)
    for annotation in design.backbone_annotations:
        feature = json.loads(annotation)
        locations = [
            sbol3.Range(
                sequence,
                start + 1,
                end,
                orientation=sbol3.SBOL_REVERSE_COMPLEMENT if strand == -1 else sbol3.SBOL_INLINE,
            )
            for start, end, strand in feature["parts"]
        ]
        label = (
            feature["qualifiers"].get("label")
            or feature["qualifiers"].get("gene")
            or [feature["type"]]
        )[0]
        role = "SO:0000316" if feature["type"] == "CDS" else "SO:0000804"
        construct.features.append(
            sbol3.SequenceFeature(
                locations=locations, roles=[_ONTOLOGY_URI["SO"].format(accession=role)], name=label
            )
        )
    document.add(construct)
    return document.write_string(sbol3.SORTED_NTRIPLES).encode("utf-8")
