# Generated by Django 5.2.17 on 2026-09-11 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='"laptop", "snakemake-prod"', max_length=100)),
                ('prefix', models.CharField(db_index=True, help_text='e.g. cern_live_7Kd2 — the first 14 characters of the secret.', max_length=16, unique=True)),
                ('key_hash', models.CharField(help_text='sha256 hexdigest.', max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list, help_text='["read"] or ["read", "design"].')),
                ('max_concurrent_runs', models.PositiveSmallIntegerField(default=2)),
                ('rate_per_minute', models.PositiveSmallIntegerField(default=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='accounts_ap_owner_i_f4faa9_idx')],
            },
        ),
    ]
