# Generated by Django 5.2.17 on 2026-08-25 20:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(help_text='Re-submitting with the same key returns the existing run rather than launching a second computation.', max_length=64, unique=True)),
                ('params_snapshot', models.JSONField(default=dict, help_text='The complete normalized configuration, frozen at submission time.')),
                ('gate_families', models.JSONField(default=list)),
                ('scoring_profile', models.CharField(default='default', max_length=50)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('stage', models.CharField(blank=True, help_text='Human-readable current stage, shown to the user.', max_length=100)),
                ('progress_pct', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cancel_requested', models.BooleanField(default=False, help_text='Cancellation is cooperative; the engine checks this between stages.')),
                ('engine_version', models.CharField(blank=True, max_length=50)),
                ('error_summary', models.TextField(blank=True, help_text='Safe to show a researcher. No tracebacks, no paths.')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='datasets.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='analyses_an_project_f32de2_idx'), models.Index(fields=['status'], name='analyses_an_status_61607a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), name='progress_pct_within_bounds')],
            },
        ),
    ]
