# Generated by Django 5.2.17 on 2026-08-26 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
        ('datasets', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='input_mode',
            field=models.CharField(choices=[('de', 'Differential expression'), ('direct', 'Direct trigger mRNA')], default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='trigger_sequence',
            field=models.TextField(blank=True, help_text='The pasted mRNA when input_mode is DIRECT.'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='Null when input_mode is DIRECT — there is no uploaded table.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='datasets.dataset'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataset__isnull', False), ('input_mode', 'de')), models.Q(('dataset__isnull', True), ('input_mode', 'direct')), _connector='OR'), name='run_has_exactly_one_input_source'),
        ),
    ]
