# Generated by Django 5.2.17 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysisrun_input_mode_analysisrun_trigger_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='organism',
            field=models.CharField(blank=True, default='ecoli', help_text='Host key: ecoli, yeast or human (engine.domain.Host). Not free text.', max_length=100),
        ),
    ]
