# Generated by Django 5.2.17 on 2026-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_alter_analysisrun_organism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='input_mode',
            field=models.CharField(choices=[('de', 'Differential expression'), ('direct', 'Direct trigger mRNA'), ('gene', 'Reference gene')], default='de', max_length=10),
        ),
    ]
