# Generated by Django 5.2.17 on 2026-10-08 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_alter_analysisrun_input_mode'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisrun',
            name='run_has_exactly_one_input_source',
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataset__isnull', False), ('input_mode', 'de')), models.Q(('dataset__isnull', True), ('input_mode__in', ('direct', 'gene'))), _connector='OR'), name='run_has_exactly_one_input_source'),
        ),
    ]
