# Generated by Django 5.2.17 on 2026-10-08 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_remove_analysisrun_run_has_exactly_one_input_source_and_more'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='idempotency_key',
            field=models.CharField(help_text='Re-submitting with the same key returns the existing run rather than launching a second computation.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(fields=('created_by', 'idempotency_key'), name='run_owner_idempotency_unique'),
        ),
    ]
